//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\YX_Tools\Code\YX_Body_info\YX_Body_info.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Yang
//              Version: NX 11
//              Date: 08-31-2016  (Format: mm-dd-yyyy)
//              Time: 10:53
//
//==============================================================================

#ifndef YX_BODY_INFO_H_INCLUDED
#define YX_BODY_INFO_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_Separator.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_StringBlock.hxx>
#include <NXOpen/BlockStyler_ObjectColorPicker.hxx>
#include <NXOpen/BlockStyler_LayerBlock.hxx>
//用户定义头文件
#include <uf.h>
#include <uf_ui.h>
#include <uf_sf.h>
#include <uf_modl.h>
#include <uf_modl_utilities.h>
#include <uf_drf.h  >
#include <algorithm>
#include <math.h>
#include <uf_obj.h>
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport YX_Body_info
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    YX_Body_info();
    ~YX_Body_info();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the YX_Body_info.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

	//用户定义的全局变量
	char msgsize[256],allvolume[256];
	double xvaule,yvaule,zvaule;
	//以下为用户定义函数
	void GetVolume();
	void PutSize();
    void HideBody();
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* GroupSelect;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* BodySelect;// Block type: Body Collector
    NXOpen::BlockStyler::Separator* separator01;// Block type: Separator
    NXOpen::BlockStyler::Toggle* ToggleHide;// Block type: Toggle
    NXOpen::BlockStyler::Group* GroupSize;// Block type: Group
    NXOpen::BlockStyler::StringBlock* StringSize;// Block type: String
    NXOpen::BlockStyler::Toggle* ToggleUpround;// Block type: Toggle
    NXOpen::BlockStyler::Group* GroupVolume;// Block type: Group
    NXOpen::BlockStyler::StringBlock* StringVolume;// Block type: String
    NXOpen::BlockStyler::Group* GroupSet;// Block type: Group
    NXOpen::BlockStyler::Toggle* Togglewindows;// Block type: Toggle
    NXOpen::BlockStyler::Separator* separator0;// Block type: Separator
    NXOpen::BlockStyler::ObjectColorPicker* ColorSet;// Block type: Color Picker
    NXOpen::BlockStyler::LayerBlock* LayerSet;// Block type: Layer
    
};
#endif //YX_BODY_INFO_H_INCLUDED
